version: '3'

services:
  backend:
    build:
      context: ./backend
    environment:
      - SCREENSHOT_DIR=/app/build/src/ui/cron/tmp
      - MONGO_URL=mongodb://mongo:27017/ta-de-rosca
      - DEBUG=cron
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo

volumes:
  mongo-data:
