version: '3'

services:
  speedtest:
    build:
      context: ./speedtest
    environment:
      - MONGO_URL=mongodb://mongo:27017/ta-de-rosca
      - DEBUG=cron
      - SCREENSHOT_SERVICE=http://screenshotstorage:3001/
      - SERVER_PORT=4001
    depends_on:
      - mongo
      - screenshotstorage

  screenshotstorage:
    build:
      context: ./screenshotstorage
    environment:
      - SCREENSHOT_DIR=/app/files
    ports:
      - 3001:3001

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo

volumes:
  mongo-data:
